// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpgSandbox.Common;

#nullable disable

namespace RpgSandbox.Migrations
{
    [DbContext(typeof(RpgDataContext))]
    [Migration("20220617230044_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("RpgSandbox.GameSystem.Entities.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnlockedAtLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("RpgSandbox.GameSystem.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InitialAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitialConstitution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitialIntellect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitialMaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitialMaxMp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitialResilience")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("RpgSandbox.GameSystem.Entities.Ability", b =>
                {
                    b.HasOne("RpgSandbox.GameSystem.Entities.Class", "Class")
                        .WithMany("Abilities")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("RpgSandbox.GameSystem.Entities.Class", b =>
                {
                    b.Navigation("Abilities");
                });
#pragma warning restore 612, 618
        }
    }
}
