// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpgSandbox.Common;

#nullable disable

namespace RpgSandbox.Migrations
{
    [DbContext(typeof(RpgDataContext))]
    [Migration("20220618224352_PartyRoles")]
    partial class PartyRoles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("ClassPartyRole", b =>
                {
                    b.Property<int>("ClassesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartyRolesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClassesId", "PartyRolesId");

                    b.HasIndex("PartyRolesId");

                    b.ToTable("ClassPartyRole");
                });

            modelBuilder.Entity("RpgSandbox.GameSystem.Entities.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnlockedAtLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Abilities");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            BaseCost = 1,
                            ClassId = 1,
                            Description = "Hits enemy with shield",
                            Name = "Shield Bash",
                            UnlockedAtLevel = 1
                        },
                        new
                        {
                            Id = 11,
                            BaseCost = 3,
                            ClassId = 1,
                            Description = "Takes damage in stead of ally",
                            Name = "Protect Ally",
                            UnlockedAtLevel = 2
                        },
                        new
                        {
                            Id = 12,
                            BaseCost = 5,
                            ClassId = 1,
                            Description = "Area attack",
                            Name = "Steelstorm",
                            UnlockedAtLevel = 3
                        },
                        new
                        {
                            Id = 20,
                            BaseCost = 1,
                            ClassId = 2,
                            Description = "Heals ally",
                            Name = "Holy Heal",
                            UnlockedAtLevel = 1
                        },
                        new
                        {
                            Id = 21,
                            BaseCost = 3,
                            ClassId = 2,
                            Description = "Sears enemy with holy light",
                            Name = "Hammer of Justice",
                            UnlockedAtLevel = 2
                        },
                        new
                        {
                            Id = 22,
                            BaseCost = 5,
                            ClassId = 2,
                            Description = "Sears all enemies in area",
                            Name = "Templar Flame",
                            UnlockedAtLevel = 3
                        },
                        new
                        {
                            Id = 30,
                            BaseCost = 1,
                            ClassId = 3,
                            Description = "A quick attack",
                            Name = "Rush",
                            UnlockedAtLevel = 1
                        },
                        new
                        {
                            Id = 31,
                            BaseCost = 3,
                            ClassId = 3,
                            Description = "Strikes the enemy several times",
                            Name = "Flourish",
                            UnlockedAtLevel = 2
                        },
                        new
                        {
                            Id = 32,
                            BaseCost = 5,
                            ClassId = 3,
                            Description = "Hits nearest 3 enemies",
                            Name = "Lord of Scoundrels",
                            UnlockedAtLevel = 3
                        },
                        new
                        {
                            Id = 40,
                            BaseCost = 1,
                            ClassId = 4,
                            Description = "Heals a small amount and removes status ailments",
                            Name = "Apply Salve",
                            UnlockedAtLevel = 1
                        },
                        new
                        {
                            Id = 41,
                            BaseCost = 3,
                            ClassId = 4,
                            Description = "Shoots arrows at all enemies in an area",
                            Name = "Sidewinder",
                            UnlockedAtLevel = 2
                        },
                        new
                        {
                            Id = 42,
                            BaseCost = 5,
                            ClassId = 4,
                            Description = "Summons animal companion",
                            Name = "Summon Companion",
                            UnlockedAtLevel = 3
                        },
                        new
                        {
                            Id = 50,
                            BaseCost = 1,
                            ClassId = 5,
                            Description = "Attacks and stuns an enemy",
                            Name = "Lightning Strike",
                            UnlockedAtLevel = 1
                        },
                        new
                        {
                            Id = 51,
                            BaseCost = 3,
                            ClassId = 5,
                            Description = "Reflects next spell cast on target",
                            Name = "Mirror Mirror",
                            UnlockedAtLevel = 2
                        },
                        new
                        {
                            Id = 52,
                            BaseCost = 5,
                            ClassId = 5,
                            Description = "A devastating area attack",
                            Name = "Bloodcrown",
                            UnlockedAtLevel = 3
                        },
                        new
                        {
                            Id = 60,
                            BaseCost = 1,
                            ClassId = 6,
                            Description = "Heals and removes status ailments",
                            Name = "Innerforce",
                            UnlockedAtLevel = 1
                        },
                        new
                        {
                            Id = 61,
                            BaseCost = 3,
                            ClassId = 6,
                            Description = "Temporarily stuns an enemy",
                            Name = "Flock of Ravens",
                            UnlockedAtLevel = 2
                        },
                        new
                        {
                            Id = 62,
                            BaseCost = 5,
                            ClassId = 6,
                            Description = "Heals all allies in an area",
                            Name = "Goddess Blessing",
                            UnlockedAtLevel = 3
                        });
                });

            modelBuilder.Entity("RpgSandbox.GameSystem.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InitialAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitialConstitution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitialIntellect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitialMaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitialMaxMp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitialResilience")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A heavy hitting fighter",
                            ImageUrl = "classes/warrior.png",
                            InitialAttack = 6,
                            InitialConstitution = 5,
                            InitialIntellect = 2,
                            InitialMaxHp = 30,
                            InitialMaxMp = 10,
                            InitialResilience = 3,
                            Name = "Warrior"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A holy knight",
                            ImageUrl = "classes/paladin.png",
                            InitialAttack = 4,
                            InitialConstitution = 5,
                            InitialIntellect = 3,
                            InitialMaxHp = 30,
                            InitialMaxMp = 10,
                            InitialResilience = 4,
                            Name = "Paladin"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A versatile fighter",
                            ImageUrl = "classes/swashbuckler.png",
                            InitialAttack = 5,
                            InitialConstitution = 4,
                            InitialIntellect = 4,
                            InitialMaxHp = 30,
                            InitialMaxMp = 10,
                            InitialResilience = 3,
                            Name = "Swashbuckler"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A hunter and tracker",
                            ImageUrl = "classes/ranger.png",
                            InitialAttack = 4,
                            InitialConstitution = 4,
                            InitialIntellect = 4,
                            InitialMaxHp = 30,
                            InitialMaxMp = 10,
                            InitialResilience = 4,
                            Name = "Ranger"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A powerful magician",
                            ImageUrl = "classes/sorcerer.png",
                            InitialAttack = 3,
                            InitialConstitution = 3,
                            InitialIntellect = 5,
                            InitialMaxHp = 30,
                            InitialMaxMp = 10,
                            InitialResilience = 5,
                            Name = "Sorcerer"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A nature mystic",
                            ImageUrl = "classes/druid.png",
                            InitialAttack = 3,
                            InitialConstitution = 4,
                            InitialIntellect = 4,
                            InitialMaxHp = 30,
                            InitialMaxMp = 10,
                            InitialResilience = 5,
                            Name = "Druid"
                        });
                });

            modelBuilder.Entity("RpgSandbox.GameSystem.Entities.PartyRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PartyRoles");
                });

            modelBuilder.Entity("ClassPartyRole", b =>
                {
                    b.HasOne("RpgSandbox.GameSystem.Entities.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpgSandbox.GameSystem.Entities.PartyRole", null)
                        .WithMany()
                        .HasForeignKey("PartyRolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgSandbox.GameSystem.Entities.Ability", b =>
                {
                    b.HasOne("RpgSandbox.GameSystem.Entities.Class", "Class")
                        .WithMany("Abilities")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("RpgSandbox.GameSystem.Entities.Class", b =>
                {
                    b.Navigation("Abilities");
                });
#pragma warning restore 612, 618
        }
    }
}
